// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EventsController from "./events_controller"
application.register("events", EventsController)

import QuestionsController from "./questions_controller"
application.register("questions", QuestionsController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)

import StepReservaController from "./step_reserva_controller"
application.register("step-reserva", StepReservaController)
